version: '3.8'
services:
  android-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/outputs/apk:/app/apk
    networks:
      - app_network


  fastapi-backend:
    build:
      context: app/src/main/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge